// edge-apps/google-calendar/src/components/monthly-calendar-view.jsx
import '@/scss/monthly-calendar-view.scss'
import { useState, useEffect } from 'react'
import { getFormattedTime } from '@/utils'

const MAX_EVENTS = 7

const MonthlyCalendarView = ({
  currentDayOfWeek,
  events = [],
  locale = 'en-US'
}) => {
  const [filteredEvents, setFilteredEvents] = useState([])
  const [formattedEventTimes, setFormattedEventTimes] = useState({})

  useEffect(() => {
    // Filter events for next 24 hours
    const now = new Date()
    const tomorrow = new Date(now)
    tomorrow.setHours(now.getHours() + 24)

    const upcomingEvents = events.filter((event) => {
      const eventStart = new Date(event.startTime)
      return eventStart >= now && eventStart < tomorrow
    })

    // Sort events by start time
    upcomingEvents.sort((a, b) => new Date(a.startTime) - new Date(b.startTime))
    const limitedEvents = upcomingEvents.slice(0, MAX_EVENTS)
    setFilteredEvents(limitedEvents)

    // Format times for all events
    const times = {}
    upcomingEvents.forEach(event => {
      getFormattedTime(new Date(event.startTime), locale)
        .then(formattedTime => {
          times[event.startTime] = formattedTime
          setFormattedEventTimes(prev => ({ ...prev, ...times }))
        })
    })
  }, [events, locale])

  return (
    <div className='MonthlyCalendarView primary-card'>
      <div className='events-heading'>
        <h1>{currentDayOfWeek}</h1>
      </div>
      <div className='events-container'>
        {filteredEvents.length > 0
          ? (
              filteredEvents.map((event, index) => (
                <div key={index} className='event-row'>
                  <div className='event-time'>
                    {formattedEventTimes[event.startTime] || '...'}
                  </div>
                  <div className='event-details'>
                    <div className='event-title'>
                      <span className='event-dot'>•</span>
                      {event.title}
                    </div>
                  </div>
                </div>
              ))
            )
          : (
            <div className='no-events'>No events scheduled for next 24 hours</div>
            )}
      </div>
    </div>
  )
}

export default MonthlyCalendarView

// edge-apps/calendar/src/components/MonthlyCalendarView.vue
<script setup lang="ts">
import { ref, watch, computed } from 'vue'
import { useCalendarStore } from '@/stores/calendar'
import { getFormattedTime } from '@/utils'
import type { CalendarEvent } from '@/constants'
import dayjs from 'dayjs'
import utc from 'dayjs/plugin/utc'
import dayJsTimezone from 'dayjs/plugin/timezone'

dayjs.extend(utc)
dayjs.extend(dayJsTimezone)

const MAX_EVENTS = 7

const calendarStore = useCalendarStore()

interface Props {
  timezone?: string
}

const props = withDefaults(defineProps<Props>(), {
  timezone: 'UTC',
})

const todayEvents = ref<CalendarEvent[]>([])
const tomorrowEvents = ref<CalendarEvent[]>([])
const formattedEventTimes = ref<Record<string, string>>({})

const currentDayOfWeek = computed(() => calendarStore.currentDayOfWeek)
const events = computed(() => calendarStore.events)
const locale = computed(() => calendarStore.locale)

const filterAndFormatEvents = async () => {
  // Get current time in the target timezone
  const nowInTimezone = dayjs().tz(props.timezone)
  const todayInTimezone = nowInTimezone.startOf('day')
  const tomorrowInTimezone = todayInTimezone.add(1, 'day')

  // Filter today's events (from now until end of today)
  const todayEventsList = events.value.filter((event: CalendarEvent) => {
    const eventStart = dayjs(event.startTime).tz(props.timezone)
    return (
      eventStart.isAfter(nowInTimezone) &&
      eventStart.isBefore(tomorrowInTimezone)
    )
  })

  // Filter tomorrow's events (full day tomorrow)
  const dayAfterTomorrow = tomorrowInTimezone.add(1, 'day')
  const tomorrowEventsList = events.value.filter((event: CalendarEvent) => {
    const eventStart = dayjs(event.startTime).tz(props.timezone)
    return (
      eventStart.isAfter(tomorrowInTimezone) &&
      eventStart.isBefore(dayAfterTomorrow)
    )
  })

  // Sort events by start time
  const sortByStartTime = (a: CalendarEvent, b: CalendarEvent) => {
    return (
      dayjs(a.startTime).tz(props.timezone).valueOf() -
      dayjs(b.startTime).tz(props.timezone).valueOf()
    )
  }

  todayEventsList.sort(sortByStartTime)
  tomorrowEventsList.sort(sortByStartTime)

  // Distribute events to maintain total around MAX_EVENTS
  let limitedTodayEvents: CalendarEvent[]
  let limitedTomorrowEvents: CalendarEvent[]

  if (todayEventsList.length >= MAX_EVENTS) {
    // If today has 7+ events, show only today's events
    limitedTodayEvents = todayEventsList.slice(0, MAX_EVENTS)
    limitedTomorrowEvents = []
  } else {
    // Show all of today's events and fill remaining slots with tomorrow's events
    limitedTodayEvents = todayEventsList
    const remainingSlots = MAX_EVENTS - todayEventsList.length
    limitedTomorrowEvents = tomorrowEventsList.slice(0, remainingSlots)
  }

  todayEvents.value = limitedTodayEvents
  tomorrowEvents.value = limitedTomorrowEvents

  // Format times for all events
  const times: Record<string, string> = {}
  const allEvents = [...limitedTodayEvents, ...limitedTomorrowEvents]

  for (const event of allEvents) {
    try {
      const formattedTime = await getFormattedTime(
        dayjs(event.startTime).tz(props.timezone).toDate(),
        locale.value,
        props.timezone,
      )
      times[event.startTime] = formattedTime
    } catch {
      times[event.startTime] = '...'
    }
  }
  formattedEventTimes.value = { ...formattedEventTimes.value, ...times }
}

watch([events, locale, () => props.timezone], filterAndFormatEvents, {
  immediate: true,
})
</script>

<template>
  <div class="MonthlyCalendarView primary-card">
    <div class="events-heading">
      <h1>{{ currentDayOfWeek }}</h1>
    </div>
    <div class="events-container">
      <div v-for="(event, index) in todayEvents" :key="index" class="event-row">
        <div class="event-time">
          {{ formattedEventTimes[event.startTime] || '...' }}
        </div>
        <div class="event-title">
          <span class="event-dot">•</span>
          {{ event.title }}
        </div>
      </div>
      <div v-if="todayEvents.length === 0" class="no-events">
        No events scheduled for today
      </div>
    </div>

    <div v-if="tomorrowEvents.length > 0" class="events-heading">
      <h1>TOMORROW</h1>
    </div>
    <div v-if="tomorrowEvents.length > 0" class="events-container">
      <div
        v-for="(event, index) in tomorrowEvents"
        :key="index"
        class="event-row"
      >
        <div class="event-time">
          {{ formattedEventTimes[event.startTime] || '...' }}
        </div>
        <div class="event-title">
          <span class="event-dot">•</span>
          {{ event.title }}
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped src="@/assets/monthly-calendar-view.scss"></style>
