// edge-apps/google-calendar/src/components/calendar-overview.jsx
import React, { useEffect, useState } from 'react';

const CalendarOverview = ({ currentDate, currentMonthName, currentYear, currentTime, events }) => {
  const [formattedTime, setFormattedTime] = useState('');
  const [filteredEvents, setFilteredEvents] = useState([]);

  useEffect(() => {
    const updateTime = async () => {
      const time = await currentTime;
      setFormattedTime(time);
    };
    updateTime();
  }, [currentTime]);

  useEffect(() => {
    // Filter events for next 24 hours
    const now = new Date();
    const tomorrow = new Date(now);
    tomorrow.setHours(now.getHours() + 24);

    const upcomingEvents = events.filter(event => {
      const eventStart = new Date(event.startTime);
      return eventStart >= now && eventStart < tomorrow;
    });

    setFilteredEvents(upcomingEvents);
  }, [events]);

  return (
    <div className="secondary-card calendar-overview-card">
      <div className="calendar-top">
        <div className="calendar-date">
          <span className="date-number-circle">{currentDate}</span>
          <span className="month-name">{currentMonthName} {currentYear}</span>
        </div>
        <div className="calendar-event">
          {filteredEvents.length > 0 ? (
            filteredEvents.map((event, index) => <p key={index}>{event.title}</p>)
          ) : (
            <p>Nothing scheduled in next 24 hours</p>
          )}
        </div>
      </div>
      <div className="calendar-bottom">
        <h1 className="calendar-time">{formattedTime}</h1>
      </div>
    </div>
  );
};

export default CalendarOverview;

// edge-apps/google-calendar-temp/src/components/calendar-overview.jsx
import { createSignal, createEffect } from 'solid-js'

const CalendarOverview = (props) => {
  const [formattedTime, setFormattedTime] = createSignal('')
  const [filteredEvents, setFilteredEvents] = createSignal([])

  createEffect(async () => {
    const time = await props.currentTime
    setFormattedTime(time)
  })

  createEffect(() => {
    // Filter events for next 24 hours
    const now = new Date()
    const tomorrow = new Date(now)
    tomorrow.setHours(now.getHours() + 24)

    const upcomingEvents = props.events.filter((event) => {
      const eventStart = new Date(event.startTime)
      return eventStart >= now && eventStart < tomorrow
    })

    setFilteredEvents(upcomingEvents)
  })

  return (
    <div class='secondary-card calendar-overview-card'>
      <div class='calendar-top'>
        <div class='calendar-date'>
          <span class='date-number-circle'>{props.currentDate}</span>
          <span class='month-name'>
            {props.currentMonthName} {props.currentYear}
          </span>
        </div>
        <div class='calendar-event'>
          {filteredEvents().length > 0
            ? (
                filteredEvents().map((event, index) => (
                  <p key={index}>{event.title}</p>
                ))
              )
            : (
              <p>Nothing scheduled in next 24 hours</p>
              )}
        </div>
      </div>
      <div class='calendar-bottom'>
        <h1 class='calendar-time'>{formattedTime()}</h1>
      </div>
    </div>
  )
}

export default CalendarOverview
