// edge-apps/google-calendar/src/components/InfoCard.vue
<template>
  <div class="secondary-card info-card">
    <img
      id="brand-logo"
      src="/img/screenly.svg"
      class="brand-logo"
      alt="Brand Logo"
    />
    <span class="info-text">Powered by Screenly</span>
  </div>
</template>

<script setup lang="ts">
// No props or logic needed for this simple component
</script>

<style scoped>
/* Component-specific styles if needed */
</style>

// edge-apps/google-calendar/src/components/info-card.jsx
const InfoCard = () => {
  return (
    <div className='secondary-card info-card'>
      <img
        id='brand-logo'
        src='img/screenly.svg'
        className='brand-logo'
        alt='Brand Logo'
      />
      <span className='info-text'>Powered by Screenly</span>
    </div>
  )
}

export default InfoCard
